logging:
  level:
    org.springframework.boot.context.config: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: auth_user
    password: auth_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
